import images from '~/assets/images';

const hotels = [
    {
        id: 1,
        name: 'One and Only Mandarina',
        username: 'mandarina',
        image: images.oneOnlyMandarina,
        address: 'Riviera Nayarit, Mexico',
        price: 1450,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: true,
            populated: false,
            journal: false,
            hotel: true,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            "Woven seamlessly into the lush Nayarit rainforest, among ferns, elephant’s ears, and the adorable long-tailed Tejón, One and Only Mandarina’s luxury treehouses and clifftop villas dot the emerald cliffside. Enjoy palm-fringed sands, ride horses along the coastline, or stop by one of the world's most incredible resort spas.",
        hotelDetailTitle:
            'One&Only Mandarina balances unparalleled seclusion with an atmosphere only they could create. Experience a unifying environment amidst the palm-fringed sands and emerald cliffside, punctuated with lagoons and estuaries, that encourage you to reconnect with yourself, those you love and the natural world. A sanctuary of unspoiled nature, open space and cultural heritage in Mexico.',
        firstRoomTitle: 'Treehouse',
        secondRoomTitle: 'Ocean Treehouse',
        thirdRoomTitle: 'Panoramic Ocean Treehouse',
        firstHotelDetailTitleMore:
            'Take a closer look at One&Only Mandarina’s Mexican-inspired design, showcasing artisanal makers and local creators. Discover the resort’s vibrant visual influences and the rich cultural traditions behind our interiors, with insights from Studio Rick Joy and Marybel Rodriguez, Director of Interior Design for RLH.',
        secondHotelDetailTitleMore:
            'Careful consideration has been executed throughout the development through low-density planning and intelligent, sustainable design and architecture. As one of Mexico’s most awe-inspiring tropical, coastal rainforests this fascinating destination boasts a swimmable white-sand beach, twin mountain peaks, lush flatlands and estuary.',
    },
    {
        id: 2,
        name: 'Es Raco dArta',
        username: 'esRoca',
        image: images.esRoca,
        address: 'Mallorca, Spain',
        price: 415,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'This unique country enclave, situated on one of the largest rural estates on the island, masterfully transforms a 13th century Mallorcan finca into a refined wellness-oriented retreat.',
        hotelDetailTitle:
            'Es Racó d’Artà is a destination where you can enjoy unique experiences, where you can reconnect with yourself through the Mallorcan way of life. Immerse yourself in local cooking, agriculture or handicrafts through the workshops; enjoy time for yourself through meditation exercises and spa treatments, or get lost in the surroundings with our group routes.',
        firstRoomTitle: 'Junior Suite Terrace',
        secondRoomTitle: 'Suite Terrace',
        thirdRoomTitle: 'Suite Terrace 360',
        firstHotelDetailTitleMore:
            'Since the 19th century, spinning and weaving mills have been prominent on the island. Hemp, linen, cotton, wool and silk looms were produced. Today Es Racó celebrates all these materials and textures through the fabrics present in all the rooms of the estate.',
        secondHotelDetailTitleMore:
            'A place that was born as a dream of its creators who, inspired by the environment, nature and the essence of the island, have turned Es Racó into their most personal legacy. A melting pot of colours and textures, a thousand and one smells and flavours, music created by the sounds of nature... in connection with art and architecture through respect and sustainability.',
    },
    {
        id: 3,
        name: 'Kalesma',
        username: 'kalesma',
        image: images.kalesma,
        address: 'Mýkonos, Greece',
        price: 630,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: true,
            journal: false,
            hotel: true,
        },
        journal: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'This tranquil, sun-drenched luxury retreat is a sophisticated favorite for discerning travelers looking to embrace the Island’s soulful cycladic heritage and laid-back glamour.',
        hotelDetailTitle:
            'The Mykonian region of Aleomandra is named after the sacred Delian stables that, according to myth, provided shelter to the horses of the Olympic god Apollo. Centuries later, Kalesma Mykonos rises out of that same Mykonian earth to become one with the legends. Both the architecture and design of Kalesma were inspired by the laid-back glamour of Mykonos, with its whitewashed walls, neutral, earthy color palette and Cycladic aesthetic.',
        firstRoomTitle: 'Villa Kalesma',
        secondRoomTitle: 'Villa Apollon',
        thirdRoomTitle: 'Villa Artemis',
        fourthRoomTitle: 'Villa Leto',
        firstHotelDetailTitleMore:
            "Kalesma's Authentic Philoxenia. “Philoxenia” is a Greek word translating to “friend to the stranger,” and the team embodies that phrase. The true “philoxenia” experience is fundamentally linked to feelings of familiarity, comfort, relaxation, and happiness.",
        secondHotelDetailTitleMore:
            'Designed by K-Studio, Kalesma’s overall aesthetic effortlessly blurs the line between indoors and out, as the open-air concept allows guests to constantly interact with the surrounding scenery and to take in the breathtaking views of the Aegean Sea.',
    },
    {
        id: 4,
        name: 'Further Diffused Hotel',
        username: 'futherDiffused',
        image: images.futherDiffusedHotel,
        address: 'Bali, Indonesia',
        price: 200,
        maxPeople: 4,
        area: 650,
        rooms: 2,
        bathrooms: 2,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Diverging from the conventional hospitality typology, Further takes the form of a diffused hotel, reimagining a long-lost concept that disperses the elements of a guest experience – rarefied spaces for sleep, rejuvenation, and celebration – throughout a village, respectfully weaving into the fabric of its community.',
        hotelDetailTitle:
            'Centred in lively Pererenan, the ascendant darling of Bali thats brimming with the places to be, Furthers four sites form a singular concept, each pairing intimate guest suites with common spaces attune to vibrant local sights, sounds, and rhythms. In the transitions between experiences, opportunities catalyse for encounters, exchange and togetherness.',
        firstRoomTitle: 'Studio Suite',
        secondRoomTitle: 'King Suite',
        thirdRoomTitle: 'Deluxe Suite',
        fourthRoomTitle: 'Family Suite',
        firstHotelDetailTitleMore:
            'As the nucleus of Further, rooms and suites take subtle cues from the layered approach of traditional Balinese architecture, inviting guests to cross the threshold into an interior world that’s both private and present to the elements. Suites are composed as the inverse of a typical room. A semi-open bathing area is situated between a permeable screen from the sleeping area, the heart of the space. Natural light, gentle breezes and tropical greenery filter into quiet interiors styled by Studio Wenden, whose considered design vernacular applies a restrained luxury that foregrounds provenance.',
        secondHotelDetailTitleMore:
            '“Through its layout and footprint, Further relates to the multi-layered street activities of the village, which evolve and change on a seasonal basis. On the other hand, Through their manifestation and architecture however, the Further buildings speak to the spiritual fabric of the place, by engaging with the presence, materiality and regular geometry of the small temples that are found in the area. Such a relationship is supported by the character of muted monumentality that the hotel displays, generating a timeless and lasting quality.” – MORQ',
    },
    {
        id: 5,
        name: 'Canoneta Townhouse',
        username: 'townhouse',
        image: images.townhouse,
        address: 'Riviera Nayarit, Mexico',
        price: 1450,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: true,
            hotel: false,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Kobu sat down for a virtual chat with forward-thinking property developers Berrow Projects, whose latest restoration project the Canoneta Townhouse is well underway in the beautiful town of Sóller, Mallorca.',
    },
    {
        id: 6,
        name: 'Musée Yves Saint Laurent Marrakech',
        username: 'laurentMarrakech',
        image: images.laurentMarrakech,
        address: 'Riviera Nayarit, Mexico',
        price: 1450,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: true,
            hotel: false,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'A visit to Marrakech is incomplete without a stop at the Musée Yves Saint Laurent. The mesmerising museum is adjacent to the vivid Jardin Majorelle and Villa Oasis, once the Marrakech home of fashion designer Yves Saint Laurent (1936-2008) and his business and life partner Pierre Bergé (1930-2017). The pair were both greatly inspired by the city, and the museum opened in 2017 as a permanent home for Yves Saint Laurent’s extensive collection of clothing, haute couture accessories, sketches and objects.',
    },
    {
        id: 7,
        name: 'Tulum Treehouse',
        username: 'tulumTreehouse',
        image: images.tulumTreehouse,
        address: 'Tulum Treehouse, Mexico',
        price: 280,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Nestled within the lush Sian Ka’an Biosphere Reserve, this jungle guest house is also a residency for artisans, chefs, designers working within Mexican craft traditions.',
        hotelDetailTitle:
            'While Tulum has become a go-to for bachelorette parties and nightclubs, its original magic still exists if you know where to look. Tulum Treehouse is proof that Tulum hasn’t lost its vibe. Originally a private villa, TTH has transformed into a 4 room guesthouse celebrating slow living. An in-house chef, minimalist jungle vibes, and nightly rooftop gatherings bring together the best of what Tulum has to offer.',
        firstRoomTitle: 'Salon Room',
        secondRoomTitle: 'Garden Room',
        thirdRoomTitle: 'Master Suite',
        fourthRoomTitle: 'Jungle Room',
        firstHotelDetailTitleMore:
            'Part exhibition, store, art studio, and kitchen which “uses the artisanal traditions and craftsmanship of the Yucatan region as a blank canvas for creative expression and collaboration”.',
        secondHotelDetailTitleMore:
            'Designed by famous Annabell Kutucu & Tulum-based architecture studio Co-lab Design Office, who worked solely with locally sourced natural materials.',
    },
    {
        id: 8,
        name: 'Koto Cabins',
        username: 'kotoCabins',
        image: images.kotoCabins,
        address: 'Belgium',
        price: 1450,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: true,
            hotel: false,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            "Woven seamlessly into the lush Nayarit rainforest, among ferns, elephant’s ears, and the adorable long-tailed Tejón, One and Only Mandarina’s luxury treehouses and clifftop villas dot the emerald cliffside. Enjoy palm-fringed sands, ride horses along the coastline, or stop by one of the world's most incredible resort spas.",
    },
    {
        id: 9,
        name: 'andBeyond Tengile River',
        username: 'tengileRiver',
        image: images.andBeyond,
        address: 'Sabi Sand, South Africa',
        price: 2000,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Situated in a perfect position on the banks of the Sand River, with sweeping river views from every vantage point, lies Tengile River Lodge. Meaning ‘tranquil’ in the local language, the lodge certainly has an advantage over all hotel in the Sabi Sand Game Reserve.',
        hotelDetailTitle:
            'This magnificent lodge features nine enormous, air-conditioned, secluded suites, dotted in the dappled shade of the bushveld, each with panoramic river views. In addition to a master bedroom, bathroom and outdoor shower, there is a lounge, dining area, fully-stocked bar, coffee station and outdoor seating and dining area that guaranteed to take your breath away. A private lap pool on your spacious private deck comes complete with sunken outdoor lounge looking out onto the famed Sand River. For families, two of the lodge’s suites are joined by a covered walkway to create a family suite.',
        firstRoomTitle: 'Suite',
        secondRoomTitle: 'Family Suite',
        firstHotelDetailTitleMore:
            'In addition to incredible leopard viewing, the famous Big Five, rhino and cheetah, discover a vast variety of plant and animal species that share the land with the Kruger National Park. Encounter a few of the over 500 bird species, 145 animal species, 110 reptile species and 45 fish species.',
        secondHotelDetailTitleMore:
            'The Sabi Sand Game Reserve is one of the most prestigious wildlife sanctuaries in the world, neighbouring the Kruger National Park. It is famed for its leopards and incredible wildlife. The uniqueness of the lodge is its ideal positioning on the Sand River with exclusive access to the riverbed.',
    },
    {
        id: 10,
        name: 'il Sereno Lago di Como',
        username: 'serenoLago',
        image: images.serenoLago,
        address: 'Como, Italy',
        price: 750,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: true,
            journal: false,
            hotel: true,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Bringing new meaning to luxury and modern design, Il Sereno Hotel breathes fresh air into the iconic, bucket list item, that is Lake Como.',
        hotelDetailTitle:
            'The, award-winning designer, Patricia Urquiola has combined the natural ambiance of the surrounding environment with comfort and luxury, resulting in a design that embodies all spectrum’s of luxurious accommodation. The 40 spacious suites, ranging from 50 square meters in size to the Penthouse at 200+ square meters, all make full use of the natural light and awe-inspiring scenery with floor-to-ceiling windows and views of the peaceful waterfront. Keeping with the Sereno promise that there is no substitute for space and a view, this intimate yet sophisticated property complements the breath-taking mountains, and tranquil waters with ease.',
        firstRoomTitle: 'Lario Suite',
        secondRoomTitle: 'Alcova Suite',
        thirdRoomTitle: 'Piccoletta',
        fourthRoomTitle: 'Lake Garden View',
        firstHotelDetailTitleMore:
            'One of the leading names in design today, Urquiola has been commissioned by brands including Louis Vuitton, Baccarat, Panerai and Missoni, amongst many hotel. The peaceful sanctuary created by Urquiola uses the surrounding elements to ensure complete relaxation, and draws inspiration from Lake Como’s culture, lifestyle and history. Il Sereno is made largely from natural materials, including wood, stone, wool and other fabrics, to create an aesthetic full of authenticity and personality, whilst remaining timeless.',
        secondHotelDetailTitleMore:
            'Designed with rich traditional Venetian Terrazzo and Travertine stone, the restaurant features a beautiful large outdoor terrace overlooking Lake Como, including a section that is built right over the water. At the center of the restaurant, a dramatic and intricate stairwell solidifies the restaurant as a visual experience, as well as a culinary one.',
    },
    {
        id: 11,
        name: 'The Standard Ibiza',
        username: 'standardIbiza',
        image: images.standardIbiza,
        address: 'Ibiza, Spain',
        price: 200,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'From poets to pirates and disco duchesses in glamorous exile, The Standard is the newest in a long line of bold characters to make its mark on Ibiza.',
        hotelDetailTitle:
            'Fifty-three rooms and suites occupy the streamlined, white hotel a pebble’s throw from the marina, presenting a clean and calming canvas for afternoon liaisons and lazy mornings in bed.',
        firstRoomTitle: 'Plaza Suite',
        secondRoomTitle: 'Suite',
        thirdRoomTitle: 'Superme King',
        fourthRoomTitle: 'Deluxe King',
        firstHotelDetailTitleMore:
            'Glam excursions on the water, rustic tours of the Ibizan countryside, and everything in between is available at The Standard. Shake up your stay with tastings in town, hot-air balloon rides, snorkeling and more. We’ve partnered with the best guides, outfitters and lifestyle mavens on the island to bring each facet of Ibiza to life for you.',
        secondHotelDetailTitleMore:
            'The hotel’s street-level restaurant Jara throws open the doors to beautiful strangers and the buzzing street scene, while guests enjoy farm-to-table cuisine and fresh cocktails, café-style. In the evening, Jara is a social and culinary destination, upping the ante within intimate banquettes and closed curtains, creating an atmosphere where anything goes.',
    },
    {
        id: 12,
        name: 'Casa Cook Rhodes',
        username: 'casaCook',
        image: images.casaCookRhodes,
        address: 'Rhodes, Greece',
        price: 300,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Positioned at the foot of the Tsambika Mountain dotted with wildflowers and grazing goats, this relaxing bohemian retreat is the perfect Rhodian balance of beach and beauty.',
        hotelDetailTitle:
            'Inspired by the nomadic way of life, this property’s character comes from natural surfaces and earthy tones. Lounging pillows and hand-picked accessories add to the warm, bohemian atmosphere — a personal space in which to kick back and slow down. Casa Cook aspires to connect a new tribe of travellers – foodies, creators, trekkers, soul searchers, beach buffs, dancers, dreamers – individuals bound together by similar values and their shared quest for a deep, fulfilling experience.',
        firstRoomTitle: 'Double Standard',
        secondRoomTitle: 'Loft Suite with Veranda',
        thirdRoomTitle: 'Split Level Suite',
        firstHotelDetailTitleMore:
            'The dusty, earthy tones of...well, almost everything at Casa Cook, create a bohemian and stylish kind of chic. They use classic Greek design elements like smooth stone floors that rise up into sofas and beds. While sideboards filled with local products are in keeping with the neo-hippie, nomadic design.',
        secondHotelDetailTitleMore:
            'We love the way this property flows. The inside-outside cube-like suites and shared spaces let light stream in and air breeze around the whole hotel. Most of the buildings are bordered by water, adding to this fluidity. Lose hours, maybe even days, soaking in the carefree, drifter vibe.',
    },
    {
        id: 13,
        name: 'Zannier Hotels Sonop',
        username: 'zannierHotel',
        image: images.zannierHotel,
        address: 'Karas, Namibia',
        price: 470,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Set within our the 13,800 private acres of untouched Namibian desert wilderness, Sonop lodge with 10 tented suites is constructed on top of granite boulders in authentic 1920’s British colonial style.',
        hotelDetailTitle:
            'At Zannier Hotels Sonop, the majestic surroundings of the desert provide ample opportunities for relaxation and adventure. Breath-taking outdoor excursions are offered within the 5,600 ha of the private reserve, where oryxes, brown hyenas, rabbits, foxes, jackals, kudus and leopards roam free. Stretching from horizon to horizon, captivating beauty and boundless freedom surround you, with adventures from sunrise to sunset.',
        firstRoomTitle: 'One Bedroom Tent',
        secondRoomTitle: 'Two Bedroom Tent',
        firstHotelDetailTitleMore:
            'At Zannier Hotels Sonop, the aim is to enhance the life and well-being of each and every one of their guests. From our spa to our rooms, all the spaces have been carefully designed to provide with complete serenity and ultimate comfort. Experienced therapists create a natural, relaxing and heartfelt spa encounter. All of our treatments use only the finest natural and organic ingredients to deliver outstanding and long-lasting results.',
        secondHotelDetailTitleMore:
            'Guest can choose to wake-up with a desert yoga experience, where an experienced teacher will guide guests of all levels. At any time of the day, guests can decide to explore the desert by foot, electric bike, or horseback, accompanied by our experienced guides who will provide unique insights on the local wildlife. Night walks are also available upon request.',
    },
    {
        id: 14,
        name: 'Arijiju Retreat',
        username: 'arijijuRetreat',
        image: images.arijijuRetreat,
        address: 'Borana Conservancy, Kenya',
        price: 9500,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Arijiju’s architecture borrows from the Kenyan tradition of grouping rooms to house multi-generations, with three suites in the main house and two generous cottages along a stone pathway.',
        hotelDetailTitle:
            'An ancient olive tree provides natural shade beside the cantilevered pool, suspended above the Sieku valley and fed by our well. Stretch out on a Lamu daybed as swallows skim the surface and elephants stop to drink from the lip. Breathe in the scent of jasmine and wild basil, and allow yourself to be hypnotised by a chorus of birdsong.',
        firstRoomTitle: 'Suite One',
        secondRoomTitle: 'Suite Two',
        thirdRoomTitle: 'Suite Three',
        firstHotelDetailTitleMore:
            'Nourishment is the cornerstone of Arijiju’s philosophy. Using local, farm-reared beef and poultry, local herbs and vegetables from our organic kitchen garden, our chefs create delicious, healthy dishes with low-or-no food miles, and allow you to tailor your menus from indulgent to slimming, vegan, and/or gluten-free.',
        secondHotelDetailTitleMore:
            'Open fences and corridors allow for safe passage for animals on migration, while radio collars on elephant matriarchs and roaming lions help inform and divert human-wildlife conflict. As such, Laikipia has emerged as the only region in Kenya where wildlife numbers have increased over the past 20 years.',
    },
    {
        id: 15,
        name: 'Hotel Lou Pinet',
        username: 'louPiner',
        image: images.louPinet,
        address: 'Saint Tropez, France',
        price: 530,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: true,
            journal: false,
            hotel: true,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Inspired by the glamorous Tropezian spirit of the 60s, this slow life refuge channels nostalgia through retro-styled rooms, manicured gardens perfumed with citrus and pine, and a turquoise-tiled pool surrounded with loungers and fabric parasols.',
        hotelDetailTitle:
            'Bewitched by the place to this day, the Pariente family took over the Hotel Lou Pinet in 2017, completely transforming it with the ultimate dream team. Charles Zana and François Vieillecroze for the architecture, landscaper Jean Mus for the gardens and Beef Bar’s Riccardo Giraudi for the restaurant. In love with the South in general and the French Riviera in particular, the team members have joined forces to reinvent the Hotel Lou Pinet, as they would be a private home where friends gather for a different take on Saint-Tropez. The real one.',
        firstRoomTitle: 'Prestige Suite',
        secondRoomTitle: 'Superior Suite',
        thirdRoomTitle: 'Deluxe Junior Suite',
        fourthRoomTitle: 'Prestige Room',
        firstHotelDetailTitleMore:
            "On the soundtrack, the ever-buzzing cicadas and the wind rustling through the trees. With 360° views of luxuriant plant life, you're sure to relax in this haven of tranquillity protected from the bustling outside world.",
        secondHotelDetailTitleMore:
            'A short walk down at the bottom of the garden, the spa is designed to resemble an intimate, protective haven. A little way away, it offers the perfect seclusion, allowing guests to enjoy the sensations to the full during a massage or fitness session in the gym.',
    },
    {
        id: 16,
        name: 'Masseria Calderisi',
        username: 'masseriaCalderisi',
        image: images.masseriaCalderisi,
        address: 'Puglia, Italy',
        price: 300,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'On the edge of the lively beach life, the 17th-century farm has been revived as a charming boutique hotel, surrounded by 24 acres of olive groves, citrus and almond trees, herb gardens and vegetable beds.',
        hotelDetailTitle:
            'The traditional 17th-century farmhouse has been revived as a charming boutique hotel, surrounded by eight hectares of olive groves, citrus and almond trees, herb gardens and vegetable beds. Once a stately country estate, the spirit of that time can still be felt – cheerful, exuberant and proud.',
        firstRoomTitle: 'Calderisi Tower',
        secondRoomTitle: 'II Fortino Suite',
        thirdRoomTitle: 'Tower Suite',
        fourthRoomTitle: 'Giardino Suite',
        firstHotelDetailTitleMore:
            'Centuries-old olive trees surround the Masseria, extending over eight hectares towards the coast. Enjoy a barefoot morning under the trees, and sample our own organic olive oil made from the masseria’s harvests. Go for a walk in the olive groves and visit the masseria’s two adopted rescue donkeys that live there, enjoying an easy life relaxing in the sun.',
        secondHotelDetailTitleMore:
            'Much of the ancient Masseria was constructed from tufa stone, quarried from the grounds of the property itself. The hotel’s architectural interventions blend seamlessly with these original structures, built sympathetically in traditional whitewashed stone. Historic details such as high vaulted ceilings, stone fireplaces, and alcoves embedded in the deep walls have all been carefully preserved. The interiors combine local materials with international touches, creating a welcoming, contemporary take on a Puglian Masseria.',
    },
    {
        id: 17,
        name: 'Ecohotel El Agua',
        username: 'ecoHotel',
        image: images.ecoHotel,
        address: 'Tenerife, Spain',
        price: 470,
        maxPeople: 16,
        area: 450,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Ecohotel El Agua is a place for holistic health and healing, encompassed within an exquisite natural setting, in the peaceful historic village of Arico el Nuevo.',
        hotelDetailTitle:
            'Ecohotel El Agua is dedicated to providing peace and tranquility so that you can mindfully listen to your body and soul. Nestled within the beautiful sub-tropical valleys of southern Tenerife their intimate hotel is a place of healing and harmony. Set within the historical village of Arico El Nuevo Ecohotel El Agua promotes Hippocratic Medicine, Naturopathy and Healing Retreats in a natural and serene environment.',
        firstRoomTitle: 'Villa Olivo',
        firstHotelDetailTitleMore:
            'Naturopathy is a traditional medicine recognized worldwide as well as Chinese and Ayurvedic medicine. These three techniques are based on the same principle: there is an immaterial and intelligent energy that animates all living beings. We talk about Prana in Ayurvedic medicine, QI in Chinese medicine, and simply vital energy in naturopathy.',
        secondHotelDetailTitleMore:
            'Ecohotel El Agua is committed to helping clean the seas and oceans of our planet. Today thousands of tons of plastics are indiscriminately dumped into our oceans and hundreds of thousands of tons of ghost nets from fishermen causing an unprecedented environmental impact. With your reservation at El Ecohotel El Agua, You help to remove 200 plastic bottles from the seas and oceans, which amounts to about 2 kilos of plastic.',
    },
    {
        id: 18,
        name: 'Casa Silencio',
        username: 'casaSilencio',
        image: images.casaSilencio,
        address: 'Oaxaca, Mexico',
        price: 1000,
        maxPeople: 16,
        area: 450,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: true,
            journal: false,
            hotel: true,
        },
        convention: true,
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Nestled within the Valley of Xaaga (the Valley of Silence), this design-forward distillery hotel celebrates one of Oaxaca’s deepest traditions — Mezcal. With only six sumptuous suites, the moody allure of this stunning enclave is one of Mexico’s most unique stays.',
        hotelDetailTitle:
            'Casa Silencio is a design-forward, eco-minded distillery and luxury retreat that honors the ancient production of mezcal, a singular agave spirit born in the mountainous, Mexican state of Oaxaca. The entire 16-acre property – including its sustainable palenque (mezcal distillery) is nestled in what we call “Valle del Silencio” (Valley of Silence). Casa Silencio is much more than a place to relax. It is a modern temple to an ancient tradition, steeped in Oaxacan mysticism behind the love of craft and culture of mezcal.',
        firstRoomTitle: 'Agua',
        secondRoomTitle: 'Tierra',
        thirdRoomTitle: 'Fuego',
        fourthRoomTitle: 'Luna',
        firstHotelDetailTitleMore:
            'All six breathtaking guest suites are geometrically constructed and appointed with furniture, art, textiles and decor that offer subtle nods to the Silencio spirit. Accents include burnt wood furnishings, distressed leather touches, artisanal candles, hand-woven wool rugs, velvet upholstery, and copper lamps - produced in partnership with local artisans, craftspeople and emerging artists.',
        secondHotelDetailTitleMore:
            'Casa Silencio is the architecture behind closed doors, meaning that nothing was left over, nothing left the construction as waste. Each element of the project was reused and applied to another function. The metallic formwork was also reutilized, to avoid wasted wood left over after conventional construction.',
    },
    {
        id: 19,
        name: 'Pārocks',
        username: 'parocks',
        image: images.parocks,
        address: 'Paros, Greece',
        price: 300,
        maxPeople: 4,
        area: 650,
        rooms: 2,
        bathrooms: 2,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Pārocks Luxury Hotel & Spa is your personal retreat, nestled on a secluded cliff, on the eastern coast of Paros.',
        hotelDetailTitle:
            'One with the wild, rocky landscape that inspired its name, Parocks overlooks the infinite blue of the Aegean Sea. Five independent buildings blend naturally in with the surroundings, forming a typical Cycladic settlement, a place that respects and complements local architecture. Just unwind and experience the unforgettable and truly heartfelt hospitality that this peaceful haven has to offer.',
        firstRoomTitle: 'Garden View Suite',
        secondRoomTitle: 'Signture Sea View Suite',
        thirdRoomTitle: 'Comfort Sea View Room',
        fourthRoomTitle: 'Superior Sea View Suite',
        firstHotelDetailTitleMore:
            'To look for its people, its traditions, its flavors. All these that shape Paros’s special identity, that charming balance between the luxurious and the bohemian, the cosmopolitan and the authentic. After all it is this very balance that makes this island so interesting. No matter how many times you visit Paros, there will always be a new secret to unravel.',
        secondHotelDetailTitleMore:
            'Pārocks breaths an air of contemporary luxury into traditional Cycladic architecture. The interior design is inspired by the surrounding environment, ensuring a much-needed feeling of escape and freedom. All rooms & suites have ample outdoor dining areas with unobstructed sea views.',
    },
    {
        id: 20,
        name: 'NIHI Sumba',
        username: 'nihiSumba',
        image: images.nihiSumba,
        address: 'Sumba Island, Indonesia',
        price: 895,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'Each of 27 uniquely designed villas offers breathtaking views of the Indian Ocean and Nihiwatu Beach combined with the signature sumbanese smiles of our team to feel both at home and completely transported.',
        hotelDetailTitle:
            'Indulge in the thrill of swimming with the Sumba Sea horses, bask each of your senses at the Spa Safari™ Nihioka, a one-of-a-kind Spa experience that is not to be missed or explore uncharted waterfalls, and stand-up paddling on rivers that wind through picturesque Sumbanese villages.',
        firstRoomTitle: 'One Bedroom Villas',
        secondRoomTitle: 'Raja Mandaka Estate',
        thirdRoomTitle: 'Villa Rahasia',
        fourthRoomTitle: 'Mamole Tree House',
        firstHotelDetailTitleMore:
            'At NIHI Hotels they believe that sustainable development marries two important themes: environmental protection does not preclude economic development and that economic development must be ecologically viable now and in the long run. NIHI Sumba was born of a vision to protect and preserve the unique Sumbanese culture and empower the local communities to improve their lives.',
        secondHotelDetailTitleMore:
            'This is not an escape from everyday life. It is the return to a life well lived. Where rugged luxury meets unregulated freedom. A place to connect with something larger than oneself. A haven for the adventurer, for the wanderer. The endlessly passionate and curious. Arrive with an open heart and leave changed forever. This is a vacation with a purpose. A destination with meaning.',
    },
    {
        id: 21,
        name: 'Villa D',
        username: 'villaD',
        image: images.villaD,
        address: 'Marrakech, Morocco',
        price: 1450,
        maxPeople: 16,
        area: 650,
        rooms: 8,
        bathrooms: 8,
        group: {
            favourite: false,
            populated: false,
            journal: false,
            hotel: true,
        },
        highlights: [
            'Villa Manager',
            'Electric mini-car',
            ' Kids Friendly',
            'Headted pool',
            'Daily breakfast',
            'Daily housekeeping',
        ],
        description:
            'At the end of a majestic alley lined with olive trees, Villa D created by Studio KO emerges from a green carpet alternating vegetable garden, orchard, mani- cured lawn and desert moor, standing there with pride as this land of contrasts with the insolent beauty welcoming it.',
        hotelDetailTitle:
            'Located on the road to Ouarzazate at 15 km from Marrakech, Villa D struggles to conceal its beautiful rurality. Beautiful watchful Palm trees surround its imposing pisé / rammed earth silhouette. Its gardens extend from its dry juniper-lined walls to the edge of the snow-capped Atlas Mountains. The diversity of this landscape relentlessly resounds with the austerity of its design, as if heaven and earth, shadow and light, the sacred and the profane, the rich and the poor have agreed to be united here between the vertical and the horizontal in a secret and subtle dialogue.',
        firstRoomTitle: 'Master Suite',
        secondRoomTitle: 'Independent Suite',
        thirdRoomTitle: 'Bedroom',
        fourthRoomTitle: '',
        firstHotelDetailTitleMore:
            'Designed by Studio KO, Villa D is intended to be both friendly and welcoming, even with its undeniably minimalist cathedral-like design. More than a pure and impressive architectural statement, it remains a humble family home brimming with surprises, led by a team who has been dedicated to its success since the very beginning. Designed and conceived as such, with its multiple living rooms and its spectacular dining room, its almost monastic row of interlocking bedrooms and their commu- nal shower room, its impressive master suite on the first floor and its independent guest pavilions, Villa D will easily accommodate all arrangements and possibilities for family gatherings and friends.',
        secondHotelDetailTitleMore:
            'The 6 hectares park is ideal for a wide range of activities, with a spectacular 25-meter-long infinity pool, open or sheltered outdoor spaces in harmony with the natural landscape. Whatever your mood or desires , lunch can be taken around our masterful dining room table or simply in the shade of the olive trees on the ground, in the purest Beldi tradition , under the juniper tree filled with birds chirping, in our magnificent garden, in the shelter of the verandas bordering the swimming pool or around our delightful pool, lulled by the gentle sound of lapping water.',
    },
];

export default hotels;
